[pytest]
testpaths = tests
pythonpath = src
             src/infrastructure/django
             tests
addopts = -q -ra -p no:cacheprovider
DJANGO_SETTINGS_MODULE = config.testing
django_find_project = false
cache_dir = venv/.pytest_cache_local
# -- recommended but optional:
python_files = tests.py test_*.py *_tests.py

