from enum import StrEnum


class SharedErrorCodes(StrEnum):
    # Autorizacao
    AUTHZ_USER_LOCKED = "AUTHZ_USER_LOCKED"
    AUTHZ_INSUFFICIENT_PRIVILEGES = "AUTHZ_INSUFFICIENT_PRIVILEGES"
    AUTHZ_TENANT_MISMATCH = "AUTHZ_TENANT_MISMATCH"
    AUTHZ_OUTSIDE_WINDOW = "AUTHZ_OUTSIDE_WINDOW"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"

    # Tecnico
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
