# Generated by Django 5.2.11 on 2026-03-14 03:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentModel',
            fields=[
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False, help_text='The date and time when the record was created (UTC).', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now, editable=False, help_text='The date and time when the record was last updated (UTC).', verbose_name='Updated At')),
                ('version', models.PositiveIntegerField(db_column='version', default=1, editable=False, help_text='Optimistic concurrency version. Increment on each real update.', verbose_name='Version')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Domain identifier (UUID).', primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.UUIDField(help_text='The unique identifier of the student.', verbose_name='Student ID')),
                ('class_group_id', models.UUIDField(help_text='The unique identifier of the class group.', verbose_name='Class Group ID')),
                ('academic_period_id', models.UUIDField(help_text='The unique identifier of the academic period.', verbose_name='Academic Period ID')),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('CONCLUDED', 'Concluded')], help_text='The state of the enrollment.', max_length=20, verbose_name='State')),
                ('concluded_at', models.DateTimeField(blank=True, help_text='When the enrollment was concluded (UTC).', null=True, verbose_name='Concluded At')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the enrollment was cancelled (UTC).', null=True, verbose_name='Cancelled At')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='When the enrollment was suspended (UTC).', null=True, verbose_name='Suspended At')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'indexes': [models.Index(fields=['student_id'], name='enrollments_student_379f04_idx'), models.Index(fields=['state'], name='enrollments_state_47a03d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentTransitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False, help_text='The date and time when the record was created (UTC).', verbose_name='Created At')),
                ('transition_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the state transition (UUID).', unique=True, verbose_name='Transition ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the transition occurred (UTC).', verbose_name='Occurred At')),
                ('action', models.CharField(choices=[('CONCLUDE', 'Conclude'), ('CANCEL', 'Cancel'), ('SUSPEND', 'Suspend')], help_text='The action that triggered the state transition.', max_length=20, verbose_name='Action')),
                ('from_state', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('CONCLUDED', 'Concluded')], help_text='The state from which the transition occurred.', max_length=20, verbose_name='From State')),
                ('to_state', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('CONCLUDED', 'Concluded')], help_text='The state to which the transition was applied.', max_length=20, verbose_name='To State')),
                ('justification', models.TextField(blank=True, help_text='Optional justification for the state transition.', null=True, verbose_name='Justification')),
                ('actor_id', models.UUIDField(help_text='The unique identifier of the actor (e.g., user) who performed the transition.', verbose_name='Actor ID')),
                ('enrollment', models.ForeignKey(help_text='The enrollment associated with this state transition.', on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='academic.enrollmentmodel', verbose_name='Enrollment ID')),
            ],
            options={
                'db_table': 'enrollment_transitions',
                'indexes': [models.Index(fields=['enrollment', 'occurred_at'], name='enrollment__enrollm_0476a9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_state', models.F('to_state')), _negated=True), name='ck_transition_from_state_diff_to_state')],
            },
        ),
    ]
