# Generated by Django 5.2.11 on 2026-03-29 05:11
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentmodel',
            name='reactivated_at',
            field=models.DateTimeField(blank=True, help_text='When the enrollment was reactivated (UTC).', null=True, verbose_name='Reactivated At'),
        ),
        migrations.AlterField(
            model_name='enrollmenttransitionmodel',
            name='action',
            field=models.CharField(choices=[('CONCLUDE', 'Conclude'), ('CANCEL', 'Cancel'), ('SUSPEND', 'Suspend'), ('REACTIVATE', 'Reactivate')], help_text='The action that triggered the state transition.', max_length=20, verbose_name='Action'),
        ),
    ]
