# Generated by Django 5.2.11 on 2026-05-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmenttransitionmodel',
            name='enrollment',
        ),
        migrations.DeleteModel(
            name='EnrollmentModel',
        ),
        migrations.DeleteModel(
            name='EnrollmentTransitionModel',
        ),
    ]
