# Generated by Django 5.2.11 on 2026-03-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_enrollmentmodel_reactivated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('cancelled', 'cancelled'), ('concluded', 'concluded')], help_text='The state of the enrollment.', max_length=20, verbose_name='State'),
        ),
    ]
