# Generated by Django 5.2.11 on 2026-03-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_enrollmentmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmenttransitionmodel',
            name='action',
            field=models.CharField(choices=[('conclude', 'conclude'), ('cancel', 'cancel'), ('suspend', 'suspend'), ('reactivate', 'reactivate')], help_text='The action that triggered the state transition.', max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='enrollmenttransitionmodel',
            name='from_state',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('cancelled', 'cancelled'), ('concluded', 'concluded')], help_text='The state from which the transition occurred.', max_length=20, verbose_name='From State'),
        ),
        migrations.AlterField(
            model_name='enrollmenttransitionmodel',
            name='to_state',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('cancelled', 'cancelled'), ('concluded', 'concluded')], help_text='The state to which the transition was applied.', max_length=20, verbose_name='To State'),
        ),
    ]
