# Generated by Django 5.2.11 on 2026-04-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_enrollmenttransitionmodel_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentmodel',
            name='institution_id',
            field=models.UUIDField(default=0, help_text='The unique identifier of the institution.', verbose_name='Institution ID'),
            preserve_default=False,
        ),
    ]
