# Generated by Django 5.2.11 on 2026-05-10 03:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False, help_text='The date and time when the record was created (UTC).', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now, editable=False, help_text='The date and time when the record was last updated (UTC).', verbose_name='Updated At')),
                ('version', models.PositiveIntegerField(db_column='version', default=1, editable=False, help_text='Optimistic concurrency version. Increment on each real update.', verbose_name='Version')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Domain identifier (UUID).', primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(help_text='The type of identity (e.g., student, teacher, admin).', max_length=50, verbose_name='Identity Type')),
                ('identity_number', models.CharField(help_text='The number of the identity (e.g., student ID, employee ID).', max_length=50, verbose_name='Identity Number')),
                ('identity_issuer', models.CharField(help_text='The issuer of the identity (e.g., institution name).', max_length=255, verbose_name='Identity Issuer')),
                ('full_name', models.CharField(help_text='The full name of the user.', max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, help_text='The email address of the user.', max_length=254, null=True, unique=True, verbose_name='Email')),
                ('birth_date', models.DateField(help_text='The birth date of the user.', verbose_name='Birth Date')),
                ('guardian_id', models.UUIDField(blank=True, help_text='The unique identifier of the guardian (if applicable).', null=True, verbose_name='Guardian ID')),
                ('state', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('suspended', 'suspended'), ('inactive', 'inactive')], help_text='The state of the user.', max_length=20, verbose_name='State')),
                ('created_by', models.CharField(help_text='The user who created this user record.', max_length=255, verbose_name='Created By')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When this user record was activated (UTC).', null=True, verbose_name='Activated At')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='When this user record was suspended (UTC).', null=True, verbose_name='Suspended At')),
                ('inactivated_at', models.DateTimeField(blank=True, help_text='When this user record was inactivated (UTC).', null=True, verbose_name='Inactivated At')),
                ('unlocked_at', models.DateTimeField(blank=True, help_text='When this user record was unlocked (UTC).', null=True, verbose_name='Unlocked At')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'constraints': [models.UniqueConstraint(fields=('identity_type', 'identity_number'), name='unique_identity')],
            },
        ),
        migrations.CreateModel(
            name='UserTransitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False, help_text='The date and time when the record was created (UTC).', verbose_name='Created At')),
                ('transition_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the state transition (UUID).', unique=True, verbose_name='Transition ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the transition occurred (UTC).', verbose_name='Occurred At')),
                ('action', models.CharField(choices=[('activate', 'activate'), ('suspend', 'suspend'), ('inactivate', 'inactivate'), ('unlock', 'unlock')], help_text='The action that triggered the state transition.', max_length=20, verbose_name='Action')),
                ('from_state', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('suspended', 'suspended'), ('inactive', 'inactive')], help_text='The state from which the transition occurred.', max_length=20, verbose_name='From State')),
                ('to_state', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('suspended', 'suspended'), ('inactive', 'inactive')], help_text='The state to which the transition was applied.', max_length=20, verbose_name='To State')),
                ('justification', models.TextField(blank=True, help_text='Optional justification for the state transition.', null=True, verbose_name='Justification')),
                ('actor_id', models.UUIDField(help_text='The unique identifier of the actor (e.g., user) who performed the transition.', verbose_name='Actor ID')),
                ('user', models.ForeignKey(help_text='The user associated with this state transition.', on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='identity.usermodel', verbose_name='User ID')),
            ],
            options={
                'db_table': 'user_transitions',
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='user_transi_user_id_b2df4d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_state', models.F('to_state')), _negated=True), name='ck_user_transition_from_state_diff_to_state')],
            },
        ),
    ]
