from enum import StrEnum


class ErrorCodes(StrEnum):
    USER_NOT_FOUND = "USER_NOT_FOUND"
    JUSTIFICATION_REQUIRED = "JUSTIFICATION_REQUIRED"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    USER_NOT_ACTIVE = "USER_NOT_ACTIVE"
    STATE_INTEGRITY_VIOLATION = "STATE_INTEGRITY_VIOLATION"
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT"
    DATA_INTEGRITY_ERROR = "DATA_INTEGRITY_ERROR"
    USER_CREATION_FAILED = "USER_CREATION_FAILED"
    DUPLICATE_USER = "DUPLICATE_USER"
    DATABASE_ERROR = "DATABASE_ERROR"
    MISSING_TRANSITIONS = "MISSING_TRANSITIONS"
    USER_REQUIRED_GUARDIAN = "USER_REQUIRED_GUARDIAN"

    
