from enum import StrEnum


class ErrorCodes(StrEnum):
    ENROLLMENT_NOT_FOUND = "ENROLLMENT_NOT_FOUND"
    JUSTIFICATION_REQUIRED = "JUSTIFICATION_REQUIRED"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    ENROLLMENT_NOT_ACTIVE = "ENROLLMENT_NOT_ACTIVE"
    CONCLUSION_NOT_ALLOWED = "CONCLUSION_NOT_ALLOWED"
    STATE_INTEGRITY_VIOLATION = "STATE_INTEGRITY_VIOLATION"
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT"
    DATA_INTEGRITY_ERROR = "DATA_INTEGRITY_ERROR"
    ENROLLMENT_CREATION_FAILED = "ENROLLMENT_CREATION_FAILED"
    DUPLICATE_ENROLLMENT = "DUPLICATE_ENROLLMENT"
    DATABASE_ERROR = "DATABASE_ERROR"
    MISSING_TRANSITIONS = "MISSING_TRANSITIONS"
